services:
  vh-payment:
    container_name: vh-payment
    image: "${IMAGE_NAME}"
    restart: unless-stopped
    cpus: '0.1'
    mem_limit: 50M
    ports:
      - 8084:80
    volumes:
      - /opt/vh/vh-payment/public/config/:/usr/share/nginx/html/config/
networks:
  default:
    name: vh
    external: true
