export const SET_THEME = 'SET_THEME';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CURRENCY = 'SET_CURRENCY';
