export const SET_THEME = 'SET_THEME';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const SET_ORDER = 'SET_ORDER';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_MEMBERSHIP_DATA = 'SET_MEMBERSHIP_DATA';
export const SET_USER_PROFILE_DATA = 'SET_USER_PROFILE_DATA';
